// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingPlanner.Models;

namespace WeddingPlanner.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190821060022_WeddingPlanner")]
    partial class WeddingPlanner
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeddingPlanner.Models.Guest", b =>
                {
                    b.Property<int>("guest_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.HasKey("guest_id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("WeddingPlanner.Models.RSVP", b =>
                {
                    b.Property<int>("rsvp_id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("RSVPed");

                    b.Property<int>("guest_id");

                    b.Property<int>("wedding_id");

                    b.HasKey("rsvp_id");

                    b.HasIndex("guest_id");

                    b.HasIndex("wedding_id");

                    b.ToTable("RSVPs");
                });

            modelBuilder.Entity("WeddingPlanner.Models.Wedding", b =>
                {
                    b.Property<int>("wedding_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Creatorguest_id");

                    b.Property<string>("bride_name")
                        .IsRequired();

                    b.Property<string>("groom_name")
                        .IsRequired();

                    b.Property<string>("wedding_address")
                        .IsRequired();

                    b.Property<DateTime>("wedding_date");

                    b.HasKey("wedding_id");

                    b.HasIndex("Creatorguest_id");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("WeddingPlanner.Models.RSVP", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Guest", "Guest")
                        .WithMany("RSVPs")
                        .HasForeignKey("guest_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlanner.Models.Wedding", "Wedding")
                        .WithMany("RSVPs")
                        .HasForeignKey("wedding_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WeddingPlanner.Models.Wedding", b =>
                {
                    b.HasOne("WeddingPlanner.Models.Guest", "Creator")
                        .WithMany()
                        .HasForeignKey("Creatorguest_id");
                });
#pragma warning restore 612, 618
        }
    }
}
